### ISSUE TITLE
Trying to make it work

### ISSUE THREAD

**Issue by xseignard** [raganmd/touchdesigner-sop-to-svg#2]
Hello,

First of all thanks for your work!
I'm trying to get it to work and I have the following error:
![capture d ecran 2018-03-09 a 18 11 04](https://user-images.githubusercontent.com/515603/37219991-7083b0e2-23c5-11e8-89b6-de0b4ab3faaf.png)

Any idea? (I'm a newby about touch)

Best regards,

Xavier

**Comment by xseignard** [comment]
Hello,
Any update?

Regards

**Comment by raganmd** [comment]
Hi there. Sorry for the delay. I’ve been at an artist residency with limited time for other work. I should be able to check on this later in the week.

**Comment by xseignard** [comment]
Thanks! Looking forward to it.

**Comment by raganmd** [comment]
Hey @xseignard I think this is resolved with commit e62ab03
Try pulling the tox and seeing if it works as expected now.

**Comment by xseignard** [comment]
It works!

Thank you!
